=== django-terran/django-terran-data/data/user/country-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "__COUNTRY_NAME__": {
            "type": "string"
        },
        "__COUNTRY_A2__": {
            "type": "string"
        },
        "__COUNTRY_A3__": {
            "type": "string"
        },
        "__COUNTRY_N3__": {
            "type": "string"
        },
        "__LANGUAGE_A2__": {
            "type": "string"
        },
        "__LANGUAGES_A2__": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "address": {
            "type": "object",
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "input_layout": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "output_format": {
                    "type": "string"
                },
                "level1area_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "level2area_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "settlement_names": {
                    "type": "object",
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "postcode_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "postcode_input_pattern": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "postcode_input_example": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "street_names": {
                    "type": "object",
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": [
                                "string",
                                "array"
                            ],
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "phone": {
            "type": "object",
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "prefixes": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "\\A[0-9]+\\Z"
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "organization_id": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "abbreviations": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "person_id": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "abbreviations": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "iban": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/BZ.json
{
    "__COUNTRY_NAME__": "Belize",
    "__COUNTRY_A2__": "BZ",
    "__COUNTRY_A3__": "BLZ",
    "__COUNTRY_N3__": "084",
    "__LANGUAGE_A2__": "en",
    "__LANGUAGES_A2__": [
        "en"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement %}{{ settlement_text }}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "District"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": null,
        "postcode_input_pattern": null,
        "postcode_input_example": null,
        "street_names": {
            "en": "House number, road"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "501"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Tax Identification Number "
        },
        "abbreviations": {
            "en": "TIN"
        },
        "input_pattern": "[0-9]{6}",
        "input_example": "123456",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/IN.json
{
    "__COUNTRY_NAME__": "India",
    "__COUNTRY_A2__": "IN",
    "__COUNTRY_A3__": "IND",
    "__COUNTRY_N3__": "356",
    "__LANGUAGE_A2__": "hi",
    "__LANGUAGES_A2__": [
        "hi",
        "en",
        "bn",
        "te",
        "mr",
        "ta",
        "ur",
        "gu",
        "kn",
        "ml",
        "or",
        "pa",
        "as",
        "mai",
        "ne",
        "sat",
        "ks",
        "kok",
        "sd",
        "sd-deva",
        "kha",
        "sa"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "settlement",
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement or has_postcode %}{% if has_settlement %}{{ settlement_text }}{% if has_postcode %} - {% endif %}{% endif %}{% if has_postcode %}{{ postcode_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "State / Territory"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{6}",
        "postcode_input_example": "123456",
        "street_names": {
            "en": "House number, road, district"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "91"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Goods and Services Tax"
        },
        "abbreviations": {
            "en": "GSTIN"
        },
        "input_pattern": "[0-9]{15}",
        "input_example": "123456789012345",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/MN.json
{
    "__COUNTRY_NAME__": "Mongolia",
    "__COUNTRY_A2__": "MN",
    "__COUNTRY_A3__": "MNG",
    "__COUNTRY_N3__": "496",
    "__LANGUAGE_A2__": "mn",
    "__LANGUAGES_A2__": [
        "mn"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode %}{{ postcode_text }}\n{% endif %}{% if has_settlement %}{{ settlement_text }}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Province"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{5}",
        "postcode_input_example": "12345",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "976"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "MN[0-9]{18}",
        "input_example": "MN123456789012345678",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/IS.json
{
    "__COUNTRY_NAME__": "Iceland",
    "__COUNTRY_A2__": "IS",
    "__COUNTRY_A3__": "ISL",
    "__COUNTRY_N3__": "352",
    "__LANGUAGE_A2__": "is",
    "__LANGUAGES_A2__": [
        "is"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "level2area",
            "settlement",
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area or has_level2area %}{% if has_level1area %}{{ level1area_name }}{% if has_level2area %}, {% endif %}{% endif %}{% if has_level2area %}{{ level2area_name }}{% endif %}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Region"
        },
        "level2area_names": {
            "en": "Municipality"
        },
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{3}",
        "postcode_input_example": "123",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "354"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Value Added Tax Number",
            "is": "Virðisaukaskattsnúmer"
        },
        "abbreviations": {
            "en": "VAT No.",
            "is": "VSK"
        },
        "input_pattern": "[0-9A-Z]{5,6}",
        "input_example": "A1B2C3",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "IS[0-9]{24}",
        "input_example": "IS123456789012345678901234",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/PA.json
{
    "__COUNTRY_NAME__": "Panama",
    "__COUNTRY_A2__": "PA",
    "__COUNTRY_A3__": "PAN",
    "__COUNTRY_N3__": "591",
    "__LANGUAGE_A2__": "es",
    "__LANGUAGES_A2__": [
        "es"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "settlement",
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode %}{{ postcode_text }}\n{% endif %}{% if has_settlement %}{{ settlement_text }}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Province"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{4}",
        "postcode_input_example": "1234",
        "street_names": {
            "en": "Road, house number, district"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "507"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Single Registry of Taxpayers",
            "es": "Registro Unico de Contribuyentes"
        },
        "abbreviations": {
            "en": "SRT",
            "es": "RUC"
        },
        "input_pattern": "[0-9]{13}[A-Z]",
        "input_example": "1234567890123A",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/ID.json
{
    "__COUNTRY_NAME__": "Indonesia",
    "__COUNTRY_A2__": "ID",
    "__COUNTRY_A3__": "IDN",
    "__COUNTRY_N3__": "360",
    "__LANGUAGE_A2__": "id",
    "__LANGUAGES_A2__": [
        "id"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "level2area",
            "settlement",
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement or has_postcode %}{% if has_settlement %}{{ settlement_text }}{% if has_postcode %} {% endif %}{% endif %}{% if has_postcode %}{{ postcode_text }}{% endif %}\n{% endif %}{% if has_level1area or has_level2area %}{% if has_level1area %}{{ level1area_name }}{% if has_level2area %}, {% endif %}{% endif %}{% if has_level2area %}{{ level2area_name }}{% endif %}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Province"
        },
        "level2area_names": {
            "en": "Regency"
        },
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{5}",
        "postcode_input_example": "12345",
        "street_names": {
            "en": "Road, house number, district"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "62"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Tax ID Number",
            "id": "Nomor Pokok Wajib Pajak"
        },
        "abbreviations": {
            "en": "Tax ID",
            "id": "NPWP"
        },
        "input_pattern": "[0-9]{15}",
        "input_example": "123456789012345",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/LV.json
{
    "__COUNTRY_NAME__": "Latvia",
    "__COUNTRY_A2__": "LV",
    "__COUNTRY_A3__": "LVA",
    "__COUNTRY_N3__": "428",
    "__LANGUAGE_A2__": "lv",
    "__LANGUAGES_A2__": [
        "lv"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement or has_postcode %}{% if has_settlement %}{{ settlement_text }}{% if has_postcode %}, {% endif %}{% endif %}{% if has_postcode %}{{ postcode_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Municipality"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "LV-[0-9]{4}",
        "postcode_input_example": "LV-1234",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "371"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "VAT identification number",
            "lv": "Pievienotās vērtības nodokļa"
        },
        "abbreviations": {
            "en": "VATIN",
            "lv": "PVN"
        },
        "input_pattern": "[0-9]{11}",
        "input_example": "12345678901",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "LV[0-9]{2}[A-Z]{4}[0-9A-Za-z]{13}",
        "input_example": "LV12ABCDa1b2c3d4e5f6g",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/DK.json
{
    "__COUNTRY_NAME__": "Denmark",
    "__COUNTRY_A2__": "DK",
    "__COUNTRY_A3__": "DNK",
    "__COUNTRY_N3__": "208",
    "__LANGUAGE_A2__": "da",
    "__LANGUAGES_A2__": [
        "da",
        "de",
        "kl"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Territory"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{4}",
        "postcode_input_example": "1234",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "45"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "da": "Momsregistreringsnummer",
            "en": "VAT identification number"
        },
        "abbreviations": {
            "da": "CVR",
            "en": "VATIN"
        },
        "input_pattern": "DK[0-9]{8}",
        "input_example": "DK12345678",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "DK[0-9]{16}",
        "input_example": "DK1234567890123456",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}
