=== django-terran/django-terran-data/data/user/country-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "__COUNTRY_NAME__": {
            "type": "string"
        },
        "__COUNTRY_A2__": {
            "type": "string"
        },
        "__COUNTRY_A3__": {
            "type": "string"
        },
        "__COUNTRY_N3__": {
            "type": "string"
        },
        "__LANGUAGE_A2__": {
            "type": "string"
        },
        "__LANGUAGES_A2__": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "address": {
            "type": "object",
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "input_layout": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "output_format": {
                    "type": "string"
                },
                "level1area_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "level2area_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "settlement_names": {
                    "type": "object",
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "postcode_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "postcode_input_pattern": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "postcode_input_example": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "street_names": {
                    "type": "object",
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": [
                                "string",
                                "array"
                            ],
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "phone": {
            "type": "object",
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "prefixes": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "\\A[0-9]+\\Z"
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "organization_id": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "abbreviations": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "person_id": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "abbreviations": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "iban": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/CF.json
{
    "__COUNTRY_NAME__": "Central African Republic",
    "__COUNTRY_A2__": "CF",
    "__COUNTRY_A3__": "CAF",
    "__COUNTRY_N3__": "140",
    "__LANGUAGE_A2__": "fr",
    "__LANGUAGES_A2__": [
        "fr",
        "sg"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement %}{{ settlement_text }}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Prefectures"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": null,
        "postcode_input_pattern": null,
        "postcode_input_example": null,
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "236"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/HT.json
{
    "__COUNTRY_NAME__": "Haiti",
    "__COUNTRY_A2__": "HT",
    "__COUNTRY_A3__": "HTI",
    "__COUNTRY_N3__": "332",
    "__LANGUAGE_A2__": "ht",
    "__LANGUAGES_A2__": [
        "ht",
        "fr"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Department"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{4}",
        "postcode_input_example": "1234",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "509"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/DO.json
{
    "__COUNTRY_NAME__": "Dominican Republic",
    "__COUNTRY_A2__": "DO",
    "__COUNTRY_A3__": "DOM",
    "__COUNTRY_N3__": "214",
    "__LANGUAGE_A2__": "es",
    "__LANGUAGES_A2__": [
        "es"
    ],
    "address": {
        "input_layout": [
            "postcode",
            "level1area",
            "level2area",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement or has_level1area or has_level2area %}{% if has_settlement %}{{ settlement_text }}{% if has_level1area or has_level2area %}, {% endif %}{% endif %}{% if has_level1area %}{{ level1area_name }}{% if has_level2area %} {% endif %}{% endif %}{% if has_level2area %}{{ level2area_name }}{% endif %}\n{% endif %}{% if has_postcode %}{{ postcode_text }}{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Province"
        },
        "level2area_names": {
            "en": "Municipality"
        },
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{5}",
        "postcode_input_example": "12345",
        "street_names": {
            "en": "Road, house number, district"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "1809",
            "1829",
            "1849"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "National Taxpayer Registry",
            "es": "Registro Nacional del Contribuyente"
        },
        "abbreviations": {
            "en": "NTR",
            "es": "RNC"
        },
        "input_pattern": "[0-9]{9}",
        "input_example": "123456789",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "DO[0-9]{2}[0-9A-Za-z]{4}[0-9]{20}",
        "input_example": "DO12a1b212345678901234567890",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/VA.json
{
    "__COUNTRY_NAME__": "Vatican City",
    "__COUNTRY_A2__": "VA",
    "__COUNTRY_A3__": "VAT",
    "__COUNTRY_N3__": "336",
    "__LANGUAGE_A2__": "it",
    "__LANGUAGES_A2__": [
        "it"
    ],
    "address": {
        "input_layout": [
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode %}{{ postcode_text }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": null,
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "00120",
        "postcode_input_example": "00120",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "379"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "VA[0-9]{20}",
        "input_example": "VA12345678901234567890",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/MT.json
{
    "__COUNTRY_NAME__": "Malta",
    "__COUNTRY_A2__": "MT",
    "__COUNTRY_A3__": "MLT",
    "__COUNTRY_N3__": "470",
    "__LANGUAGE_A2__": "mt",
    "__LANGUAGES_A2__": [
        "mt",
        "en"
    ],
    "address": {
        "input_layout": [
            "postcode",
            "level1area",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement %}{{ settlement_text }}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_postcode %}{{ postcode_text }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Region"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[A-Z]{3} [0-9]{4}",
        "postcode_input_example": "ABC 1234",
        "street_names": {
            "en": "House number, road"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "356"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "VAT identification number",
            "mt": "Vat reg. no."
        },
        "abbreviations": {
            "en": "VATIN",
            "mt": "Vat No."
        },
        "input_pattern": "[0-9]{8}",
        "input_example": "12345678",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "MT[0-9]{2}[A-Z]{4}[0-9]{5}[0-9A-Za-z]{18}",
        "input_example": "MT12ABCD12345a1b2c3d4e5f6g7h8i9",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/HN.json
{
    "__COUNTRY_NAME__": "Honduras",
    "__COUNTRY_A2__": "HN",
    "__COUNTRY_A3__": "HND",
    "__COUNTRY_N3__": "340",
    "__LANGUAGE_A2__": "es",
    "__LANGUAGES_A2__": [
        "es"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Department"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[A-Z]{2}[0-9]{4}|[0-9]{5}",
        "postcode_input_example": "AB1234",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "504"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "National Tax Registry",
            "es": "Registro Tributario Nacional"
        },
        "abbreviations": {
            "en": "NTR",
            "es": "RTN"
        },
        "input_pattern": "[0-9]{14}",
        "input_example": "12345678901234",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/EC.json
{
    "__COUNTRY_NAME__": "Ecuador",
    "__COUNTRY_A2__": "EC",
    "__COUNTRY_A3__": "ECU",
    "__COUNTRY_N3__": "218",
    "__LANGUAGE_A2__": "es",
    "__LANGUAGES_A2__": [
        "es",
        "qu"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode %}{{ postcode_text }}\n{% endif %}{% if has_settlement %}{{ settlement_text }}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Province"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{6}",
        "postcode_input_example": "123456",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "593"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Unique Taxpayer Registration Number",
            "es": "NÃºmero de Registro Unico de Contribuyentes"
        },
        "abbreviations": {
            "en": "UTR",
            "es": "RUC"
        },
        "input_pattern": "[0-9]{13}",
        "input_example": "1234567890123",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/BG.json
{
    "__COUNTRY_NAME__": "Bulgaria",
    "__COUNTRY_A2__": "BG",
    "__COUNTRY_A3__": "BGR",
    "__COUNTRY_N3__": "100",
    "__LANGUAGE_A2__": "bg",
    "__LANGUAGES_A2__": [
        "bg"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "settlement",
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "bg": "Област",
            "en": "Province"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{4}",
        "postcode_input_example": "1234",
        "street_names": {
            "en": "Road, house number, district"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "359"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "bg": "Идентификационен номер по ДДС",
            "en": "VAT identification number"
        },
        "abbreviations": {
            "bg": "ДДС номер",
            "en": "VATIN"
        },
        "input_pattern": "BG[0-9]{9,10}",
        "input_example": "BG123456789",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "BG[0-9]{2}[A-Z]{4}[0-9]{6}[0-9A-Za-z]{8}",
        "input_example": "BG12ABCD123456a1b2c3d4",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}
