=== django-terran/django-terran-data/data/user/country-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "type": "object",
    "properties": {
        "__COUNTRY_NAME__": {
            "type": "string"
        },
        "__COUNTRY_A2__": {
            "type": "string"
        },
        "__COUNTRY_A3__": {
            "type": "string"
        },
        "__COUNTRY_N3__": {
            "type": "string"
        },
        "__LANGUAGE_A2__": {
            "type": "string"
        },
        "__LANGUAGES_A2__": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "address": {
            "type": "object",
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "input_layout": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "output_format": {
                    "type": "string"
                },
                "level1area_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "level2area_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "settlement_names": {
                    "type": "object",
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "postcode_names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "postcode_input_pattern": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "postcode_input_example": {
                    "type": [
                        "string",
                        "null"
                    ]
                },
                "street_names": {
                    "type": "object",
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": [
                                "string",
                                "array"
                            ],
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "phone": {
            "type": "object",
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "prefixes": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "pattern": "\\A[0-9]+\\Z"
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "organization_id": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "abbreviations": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "person_id": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "abbreviations": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "iban": {
            "type": ["object", "null"],
            "patternProperties": {
                "\\A__COMMENT_[0-9]+__\\Z": {
                    "type": "string"
                }
            },
            "properties": {
                "names": {
                    "type": [
                        "object",
                        "null"
                    ],
                    "patternProperties": {
                        "\\A[a-z]+\\Z": {
                            "type": "string"
                        }
                    }
                },
                "input_pattern": {
                    "type": "string"
                },
                "input_example": {
                    "type": "string"
                },
                "output_format": {
                    "type": "object",
                    "patternProperties": {
                        "\\A.*\\Z": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/MU.json
{
    "__COUNTRY_NAME__": "Mauritius",
    "__COUNTRY_A2__": "MU",
    "__COUNTRY_A3__": "MUS",
    "__COUNTRY_N3__": "480",
    "__LANGUAGE_A2__": "en",
    "__LANGUAGES_A2__": [
        "en",
        "fr"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "settlement",
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement or has_postcode %}{% if has_settlement %}{{ settlement_text }}{% if has_postcode %} {% endif %}{% endif %}{% if has_postcode %}{{ postcode_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "District"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{5}",
        "postcode_input_example": "12345",
        "street_names": {
            "en": "House number, road"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "230"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "MU[0-9]{2}[A-Z]{4}[0-9]{19}[A-Z]{3}",
        "input_example": "MU12ABCD1234567890123456789ABC",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/RS.json
{
    "__COUNTRY_NAME__": "Serbia",
    "__COUNTRY_A2__": "RS",
    "__COUNTRY_A3__": "SRB",
    "__COUNTRY_N3__": "688",
    "__LANGUAGE_A2__": "sr",
    "__LANGUAGES_A2__": [
        "sr",
        "sr-latn",
        "hu",
        "ro",
        "hr",
        "sk",
        "uk"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "level2area",
            "settlement",
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area or has_level2area %}{% if has_level1area %}{{ level1area_name }}{% if has_level2area %} {% endif %}{% endif %}{% if has_level2area %}{{ level2area_name }}{% endif %}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "District"
        },
        "level2area_names": {
            "en": "Municipality"
        },
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{5}",
        "postcode_input_example": "12345",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "381"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Tax Identification Number",
            "sr": "Poreski identifikacioni broj"
        },
        "abbreviations": {
            "en": "TIN",
            "sr": "PIB"
        },
        "input_pattern": "[0-9]{9}",
        "input_example": "123456789",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "RS[0-9]{20}",
        "input_example": "RS12345678901234567890",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/NO.json
{
    "__COUNTRY_NAME__": "Norway",
    "__COUNTRY_A2__": "NO",
    "__COUNTRY_A3__": "NOR",
    "__COUNTRY_N3__": "578",
    "__LANGUAGE_A2__": "nb",
    "__LANGUAGES_A2__": [
        "nb",
        "no",
        "nn",
        "se"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "County"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{4}",
        "postcode_input_example": "1234",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "47"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Organization number",
            "nb": "Organisasjonsnummer",
            "nn": "Organisasjonsnummer"
        },
        "abbreviations": {
            "en": "Org No.",
            "nb": "Orgnr",
            "nn": "Orgnr"
        },
        "input_pattern": "[0-9]{9}MVA",
        "input_example": "123456789MVA",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": {
        "names": {
            "en": "IBAN"
        },
        "input_pattern": "NO[0-9]{13}",
        "input_example": "NO1234567890123",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    }
}

=== django-terran/django-terran-data/data/user/countries/SR.json
{
    "__COUNTRY_NAME__": "Suriname",
    "__COUNTRY_A2__": "SR",
    "__COUNTRY_A3__": "SUR",
    "__COUNTRY_N3__": "740",
    "__LANGUAGE_A2__": "nl",
    "__LANGUAGES_A2__": [
        "nl"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement %}{{ settlement_text }}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "District"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": null,
        "postcode_input_pattern": null,
        "postcode_input_example": null,
        "street_names": {
            "en": "Road, house number, district"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "597"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/MM.json
{
    "__COUNTRY_NAME__": "Myanmar (Burma)",
    "__COUNTRY_A2__": "MM",
    "__COUNTRY_A3__": "MMR",
    "__COUNTRY_N3__": "104",
    "__LANGUAGE_A2__": "my",
    "__LANGUAGES_A2__": [
        "my"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement or has_postcode %}{% if has_settlement %}{{ settlement_text }}{% if has_postcode %}, {% endif %}{% endif %}{% if has_postcode %}{{ postcode_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "State / Region / Zone"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{5}",
        "postcode_input_example": "12345",
        "street_names": {
            "en": "House number, road"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "95"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/PE.json
{
    "__COUNTRY_NAME__": "Peru",
    "__COUNTRY_A2__": "PE",
    "__COUNTRY_A3__": "PER",
    "__COUNTRY_N3__": "604",
    "__LANGUAGE_A2__": "es",
    "__LANGUAGES_A2__": [
        "es",
        "qu"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "settlement",
            "postcode",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_settlement or has_postcode %}{% if has_settlement %}{{ settlement_text }}{% if has_postcode %} {% endif %}{% endif %}{% if has_postcode %}{{ postcode_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Regional Governments"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "(PE[0-9]{4})|[0-9]{5}",
        "postcode_input_example": "PE1234",
        "street_names": {
            "en": "Road, house number, district"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "51"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": {
        "names": {
            "en": "Single Registry of Taxpayers",
            "es": "Registro Unico de Contribuyentes"
        },
        "abbreviations": {
            "en": "SRT",
            "es": "RUC"
        },
        "input_pattern": "[0-9]{11}",
        "input_example": "12345678901",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/DZ.json
{
    "__COUNTRY_NAME__": "Algeria",
    "__COUNTRY_A2__": "DZ",
    "__COUNTRY_A3__": "DZA",
    "__COUNTRY_N3__": "012",
    "__LANGUAGE_A2__": "ar",
    "__LANGUAGES_A2__": [
        "ar",
        "fr"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Province"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{5}",
        "postcode_input_example": "12345",
        "street_names": {
            "en": "House number, road"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "213"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": null
}

=== django-terran/django-terran-data/data/user/countries/ET.json
{
    "__COUNTRY_NAME__": "Ethiopia",
    "__COUNTRY_A2__": "ET",
    "__COUNTRY_A3__": "ETH",
    "__COUNTRY_N3__": "231",
    "__LANGUAGE_A2__": "am",
    "__LANGUAGES_A2__": [
        "am"
    ],
    "address": {
        "input_layout": [
            "level1area",
            "postcode",
            "settlement",
            "street"
        ],
        "output_format": "{% if has_recipient %}{{ recipient_text }}\n{% endif %}{% if has_street %}{{ street_text }}\n{% endif %}{% if has_postcode or has_settlement %}{% if has_postcode %}{{ postcode_text }}{% if has_settlement %} {% endif %}{% endif %}{% if has_settlement %}{{ settlement_text }}{% endif %}\n{% endif %}{% if has_level1area %}{{ level1area_name }}\n{% endif %}{% if has_country %}{{ country_name }}\n{% endif %}",
        "level1area_names": {
            "en": "Region"
        },
        "level2area_names": null,
        "settlement_names": {
            "en": "Settlement"
        },
        "postcode_names": {
            "en": "Post Code"
        },
        "postcode_input_pattern": "[0-9]{4}",
        "postcode_input_example": "1234",
        "street_names": {
            "en": "Road, house number"
        }
    },
    "phone": {
        "names": {
            "en": "Phone Number"
        },
        "prefixes": [
            "251"
        ],
        "input_pattern": "[0-9]+",
        "input_example": "####",
        "output_format": {
            "\\A.*\\Z": "\\1"
        }
    },
    "organization_id": null,
    "person_id": null,
    "iban": null
}
